In [ ]:
2575647_Talluri janardhanakrishna

# Dataset

np_olympic_country=np.array(['GBR','Chine','RUS','US','KOR','JPN','GER'])
np_olympic_country_gold=np.array([29,38,24,46,13,7,11])
np_olympic_country_silver=np.array([17,28,25,28,8,14,11])
np_olympic_country_Bronze=np.array([19,22,32,29,7,17,14])


In [ ]:
1.find the country index with maximum gold


In [28]:
import numpy as np

# Create the dataset
np_olympic_country = np.array(['GBR', 'China', 'RUS', 'US', 'KOR', 'JPN', 'GER'])
np_olympic_country_gold = np.array([29, 38, 24, 46, 13, 7, 11])
np_olympic_country_silver = np.array([17, 28, 25, 28, 8, 14, 11])
np_olympic_country_bronze = np.array([19, 22, 32, 29, 7, 17, 14])

# 1. Find the country index with maximum gold
max_gold_index = np.argmax(np_olympic_country_gold)
print(max_gold_index)



3


In [ ]:
2. Print Country with Maximum gold


In [24]:
import numpy as np

# Create the dataset
np_olympic_country = np.array(['GBR', 'China', 'RUS', 'US', 'KOR', 'JPN', 'GER'])
np_olympic_country_gold = np.array([29, 38, 24, 46, 13, 7, 11])
np_olympic_country_silver = np.array([17, 28, 25, 28, 8, 14, 11])
np_olympic_country_bronze = np.array([19, 22, 32, 29, 7, 17, 14])

# 2. Print the country with maximum gold
country_with_max_gold = np_olympic_country[max_gold_index]
print("Country with maximum gold:", country_with_max_gold)


Country with maximum gold: US


In [ ]:
3. Find countries with more than 20 gold
medals

In [29]:
import numpy as np
# Create the dataset
np_olympic_country = np.array(['GBR', 'China', 'RUS', 'US', 'KOR', 'JPN', 'GER'])
np_olympic_country_gold = np.array([29, 38, 24, 46, 13, 7, 11])
np_olympic_country_silver = np.array([17, 28, 25, 28, 8, 14, 11])
np_olympic_country_bronze = np.array([19, 22, 32, 29, 7, 17, 14])
# 3. Find countries with more than 20 gold
countries_with_more_than_20_gold = np_olympic_country[np_olympic_country_gold > 20]
print("Countries with more than 20 gold:", countries_with_more_than_20_gold)



Countries with more than 20 gold: ['GBR' 'China' 'RUS' 'US']


In [ ]:
4. Evaluate the dataset and print the medal:

1. print each country name with number of gold medals

2. print each country nale with total number of medals


In [25]:
import numpy as np

# Create the dataset
np_olympic_country = np.array(['GBR', 'China', 'RUS', 'US', 'KOR', 'JPN', 'GER'])
np_olympic_country_gold = np.array([29, 38, 24, 46, 13, 7, 11])
np_olympic_country_silver = np.array([17, 28, 25, 28, 8, 14, 11])
np_olympic_country_bronze = np.array([19, 22, 32, 29, 7, 17, 14])
# 4. Evaluate the dataset and print the medals
# 4.1 Print each country name with the number of gold medals
for i in range(len(np_olympic_country)):
    print(np_olympic_country[i], ":", np_olympic_country_gold[i], "gold medals")

# 4.2 Print each country name with the total number of medals
total_medals = np_olympic_country_gold + np_olympic_country_silver + np_olympic_country_bronze
for i in range(len(np_olympic_country)):
    print(np_olympic_country[i], ":", total_medals[i], "total medals")

GBR : 29 gold medals
China : 38 gold medals
RUS : 24 gold medals
US : 46 gold medals
KOR : 13 gold medals
JPN : 7 gold medals
GER : 11 gold medals
GBR : 65 total medals
China : 88 total medals
RUS : 81 total medals
US : 103 total medals
KOR : 28 total medals
JPN : 38 total medals
GER : 36 total medals


# 1. Create a 3x3x3 array with random values


In [34]:
import numpy as np

array = np.random.rand(3, 3, 3)
print(array)

[[[0.63035607 0.57133537 0.46681133]
  [0.83391496 0.98820031 0.57909415]
  [0.00722112 0.15192289 0.44560363]]

 [[0.44360948 0.96131628 0.76489098]
  [0.48858203 0.40737193 0.22279239]
  [0.82722107 0.39328552 0.04683581]]

 [[0.16705864 0.36139722 0.50239102]
  [0.03978676 0.44741481 0.98554953]
  [0.19081385 0.47911802 0.97035624]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [37]:
import numpy as np

matrix = np.zeros((5, 5))
np.fill_diagonal(matrix[0:], [1, 2, 3, 4 ,5])
print(matrix)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [50]:
import numpy as np

matrix = np.zeros((8, 8), dtype=int)
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix


In [53]:
import numpy as np

matrix = np.zeros((5, 5))
np.fill_diagonal(matrix[0:], [13, 24, 33, 42 ,35])
print(matrix)
normalized_matrix = (matrix - np.mean(matrix)) / np.std(matrix)
print(normalized_matrix)

[[13.  0.  0.  0.  0.]
 [ 0. 24.  0.  0.  0.]
 [ 0.  0. 33.  0.  0.]
 [ 0.  0.  0. 42.  0.]
 [ 0.  0.  0.  0. 35.]]
[[ 0.56581831 -0.46727692 -0.46727692 -0.46727692 -0.46727692]
 [-0.46727692  1.4399758  -0.46727692 -0.46727692 -0.46727692]
 [-0.46727692 -0.46727692  2.15519557 -0.46727692 -0.46727692]
 [-0.46727692 -0.46727692 -0.46727692  2.87041534 -0.46727692]
 [-0.46727692 -0.46727692 -0.46727692 -0.46727692  2.31413329]]


# 5. How to find common values between two arrays?

In [55]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])
common_values = np.intersect1d(array1, array2)
print(array1)
print(array2)
print(common_values)

[1 2 3 4 5]
[4 5 6 7 8]
[4 5]


# 6.How to get the dates of yesterday, today andtomorrow?

In [56]:
from datetime import datetime, timedelta

today = datetime.now().date()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2023-09-20
Today: 2023-09-21
Tomorrow: 2023-09-22


# 7. Consider two random array A and B, check if they are equal


In [60]:
import numpy as np
A=[]
B=[]
A.append([1,2,3])
A.append([1,2,3])
A.append([1,2,3])
A.append([1,2,3])
A.append([1,2,3])
B.append([4,5,3])
B.append([4,5,3])
B.append([4,5,3])
B.append([4,5,3])
B.append([4,5,3])
if np.array_equal(A, B):
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")


Arrays A and B are not equal.


# 8.Create random vector of size 10 and replace the maximum value by 0

In [63]:
import numpy as np

vector = np.random.rand(10)  # Random vector of size 10
max_value = np.max(vector)  # Find the maximum value in the vector
vector[np.argmax(vector)] = 0  # Replace the maximum value with 0

print("Modified vector:", vector)

Modified vector: [0.52097316 0.2072545  0.37023018 0.10805183 0.2123479  0.64830087
 0.75426419 0.18770742 0.         0.18267943]


# 9. How to print all the values of an array?


In [66]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])  

for element in array:
    print(element)

1
2
3
4
5


# 10.Subtract the mean of each row of a matrix


In [67]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # Example matrix

mean = np.mean(matrix, axis=1)  # Calculate the mean of each row
result = matrix - mean[:, np.newaxis]  # Subtract the mean from each row

print("Result matrix:", result)


Result matrix: [[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [68]:
import numpy as np

vector = np.array([1, 2, 3, 4, 5])  # Example vector
indices = np.array([0, 1, 1, 3])  # Example indices

vector += np.bincount(indices, minlength=len(vector))

print("Modified vector:", vector)


Modified vector: [2 4 3 5 5]


# 12.How to get the diagonal of a dot product?


In [69]:
import numpy as np

matrix1 = np.array([[1, 2], [3, 4]])  # First matrix
matrix2 = np.array([[5, 6], [7, 8]])  # Second matrix

dot_product = np.dot(matrix1, matrix2)  # Calculate the dot product
diagonal = np.diag(dot_product)  # Get the diagonal elements

print("Diagonal of the dot product:", diagonal)

Diagonal of the dot product: [19 50]


# 13.How to find the most frequent value in anarray?


In [70]:
import numpy as np

def find_most_frequent_value(arr):
    unique_values, counts = np.unique(arr, return_counts=True)
    max_count_index = np.argmax(counts)
    most_frequent_value = unique_values[max_count_index]
    return most_frequent_value

my_array = np.array([1, 2, 3, 2, 1, 2, 3, 3, 3])
most_frequent = find_most_frequent_value(my_array)
print("Most frequent value:", most_frequent)

Most frequent value: 3


# 14.How to get the n largest values of an array


In [75]:
import numpy as np

def get_n_largest_values(arr, n):
    sorted_indices = np.argsort(arr)
    n_largest_indices = sorted_indices[-n:]
    n_largest_values = arr[n_largest_indices]
    return n_largest_values

my_array = np.array([5, 2, 9, 1, 7, 3])
n_largest = get_n_largest_values(my_array, 1)
print("N largest values:", n_largest)


N largest values: [9]


# 15.How to create a record array from a regular array?

In [83]:
import numpy as np

def create_record_array(regular_array):
    record_array = np.array(regular_array, dtype=[('field1', int), ('field2', float), ('field3', int)])
    return record_array

# Example usage
my_array = [[1, 2.5, 4], [2, 3.7, 8], [3, 4.2, 6]]
record_array = create_record_array(my_array)
print("Record array:", record_array)

Record array: [[(1, 1. , 1) (2, 2.5, 2) (4, 4. , 4)]
 [(2, 2. , 2) (3, 3.7, 3) (8, 8. , 8)]
 [(3, 3. , 3) (4, 4.2, 4) (6, 6. , 6)]]


# 16. How to swap two rows of an array?


In [84]:
import numpy as np

def swap_rows(arr, row1, row2):
    arr[[row1, row2]] = arr[[row2, row1]]
    return arr

# Example usage
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
swapped_array = swap_rows(my_array, 0, 2)
print("Swapped array:")
print(swapped_array)


Swapped array:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


# 17. Write python code to reshape to the next dimension of numpy array?

In [85]:
import numpy as np

def reshape_to_next_dimension(arr):
    reshaped_array = np.reshape(arr, (arr.shape[0], -1))
    return reshaped_array

# Example usage
my_array = np.array([[1, 2, 3], [4, 5, 6]])
reshaped_array = reshape_to_next_dimension(my_array)
print("Reshaped array:")
print(reshaped_array)

Reshaped array:
[[1 2 3]
 [4 5 6]]
